name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - name: ubuntu-18.04-gcc-5
            os: ubuntu-18.04
            compiler: gcc
            version: 5

    steps:
    - uses: actions/checkout@v2

    - name: Configure and make
      uses: lukka/run-cmake@v3
      with:
        cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
        buildDirectory: "${{ github.workspace }}/build"
        cmakeBuildType: 'Release'
        cmakeAppendedArgs: '-DBUILD_EXAMPLES=ON'

    - name: Run Examples (Unix)
      if: matrix.os == 'ubuntu-latest' 
      run: |
        cd ${{ github.workspace }}/build
        ./test/batotp_test

    - name: Run Examples (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd ${{ github.workspace }}\build\test
        .\Debug\batotp_test.exe 
